FROM python:3.9-slim

WORKDIR /app

# These files will be copied into the container
COPY requirements.txt .
COPY app.py .
COPY start.sh .

# Updates the OS package list and installs dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    redis-server \
    && rm -rf /var/lib/apt/lists/*

    
# SDK de Split
RUN pip install splitio_client[cpphash]==10.4.0

# Proyect dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Change execution permissions
RUN chmod +x start.sh

EXPOSE 5000

# This command will be executed when the container is initialized
CMD ["./start.sh"]