FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    redis-server \
    && rm -rf /var/lib/apt/lists/*

# SDK
RUN pip install splitio_client[cpphash]==10.4.0

EXPOSE 5000

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY start.sh .
COPY app.py .

RUN chmod +x start.sh

CMD ["./start.sh"]